### ISSUE TITLE
Umple json generation fails in certain cases when traits present

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1101]
The following code fails when attempting to generate json from it as occurs, for example, when drawing editable diagrams in UmpleOnline.

```
class Color {}

trait TDrawable {
  0..1 -> * Color color;
}

class Z {
  isA TDrawable;
}
```
This results in the compiler crashing
at JsonGenerator.extractClassName

Note that a much large example of this is the Geometric Objects example in UmpleOnline. That will generate graphviz. Somebody has special-cased the example to avoid it trying to generate Json.

People using this example regularly crash UmpleOnline, so this problem needs fixing quickly.

**Comment by JoshuaMcManus** [comment]
Was reading through the description of a Trait and noticed that the last line in the first paragraph on this page is repeated: http://cruise.eecs.uottawa.ca/umple/Traits.html

I'm not sure where to report typos like that so I'll post it here for now.

I also found that the link on the line: "Note that traits themselves are subject to being **mixed** in." returns a 404.

**Comment by vahdat-ab** [comment]
> I'm not sure where to report typos like that so I'll post it here for now.

Thank you, Josh. I fixed them and push a new branch. I'll merge it soon.

**Comment by JoshuaMcManus** [comment]
After discussing with Vahdat, there are few things to note about this issue:
1. The association defined in TDrawable still exists in the model's list of associations when generating the json - this is why the null pointed exception is thrown in extractClassName(). I believe that the only association that should exist is 0..1 Z -- * Color color. This association does exist, but it is missing its coordinates since it is applied to the class after postTokenLayoutAnalysis(). When the Json generator executes, it gives it a coordinate of (-1, -1), (-1, -1). 

Vahdat noted that the associations should be maintained at the model level for futrueproofing the project (in case it needs to be used later). So I've created a solution which just skips generating Json for any association that involves traits, which should be sufficient for solving this issue.

2. The coordinates of the associations are never set because the trait's associations are applied to a class in the function applyTraits() which is called after the postTokenLayoutAnalysis() function is executed (which generates all the coordinates for classes, associations, etc.)

I am going to have to rearrange the code somehow, which I will investigate further.

**Comment by vahdat-ab** [comment]
@AlexJoshuaMcManus  I brought back associations added to the model.
Please check the branch named `association_traits` and see if this is what you were looking for or not.
Once you confirm, I'll merge it.
Thanks

**Comment by JoshuaMcManus** [comment]
@vahdat-ab I looked over the changes and it appears to recover the associations at the model level, which is what I was hoping for. If you feel that adding this back will not compromise the architecture of the system, then please merge it. Thanks.

**Comment by vahdat-ab** [comment]
@AlexJoshuaMcManus  it's done.

**Comment by JoshuaMcManus** [comment]
Pull request was merged in
